### ISSUE TITLE
Ignore error on function connection.WriteVariables

### ISSUE THREAD

**Issue by frozen2510** [Rufus31415/Sharer.NET#1]
Looking for a wait to bypass the error checking on Connection.WriteVariables. Is this possible?

Thank You

**Comment by Rufus31415** [comment]
When WriteVariables fails, there can be 2 phenomena:
Either an exception 
Either false is returned
What case are you talking about?

For the exception, you can try/catch it in your code.

**Comment by frozen2510** [comment]
Sry, I'm new to programing. If the Arduino is busy and does not return an OK response, the C# program will crash. I'm trying to avoid this. I have used this code block and it seems to work. 
```
if (connection.WriteVariable("Arduino Var", Local Var))
            {
                Console.WriteLine("OK");

            }
            else Console.WriteLine("Failed to write variable");
```

**Comment by Rufus31415** [comment]
What do you mean by "Arduino Var"? This string contains a space, it can't be the name of a variable in your c arduino code.
