### ISSUE TITLE
Raspbian migration

### ISSUE THREAD

**Issue by braglin** [Rufus31415/Sharer.NET#2]
Hi!

I have a C# application running on Windows but for several reasons I will need to run the same application on an RPi3, I tried to run it using Mono but I'm not able to connect to Sharer on the Arduino side, it only shows a message similar to this "The serial connection is open but can't connect with Sharer", the Arduino code is working normally (tested with the application in Windows).

I downloaded your "Sharer Console for ARM" example, but I'm not quite sure about how to use it, could you share some tutorial with me?

**Comment by Rufus31415** [comment]
Hi, 
Sharer has never been tested on Mono. However, for running on Linux, .NET Core or .Net 5 must be used. The approach is the same as on Windows, you make a project in which you reference the Sharer nugget package.
Tell me if you want a detailed tutorial

**Comment by braglin** [comment]
Ok, I will install the .Net Core and try it again.... about the Console Example, all those dll and so files must be copied to my application's folder?

Thank you for your support so far!

**Comment by Rufus31415** [comment]
If you want to test the console app, you can download the zip file that contains the standalone examples.
However il you want to use Sharer in your Net Core app, you just have to reference Sharer via  nugget and that's it : https://www.nuget.org/packages/Sharer
